language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq --no-install-recommends perl autotools-dev libdbi-dev libldap2-dev libpq-dev libmysqlclient-dev libradiusclient-ng-dev libkrb5-dev libnet-snmp-perl procps mawk
    - sudo apt-get install -qq --no-install-recommends autoconf automake

script:
    - tools/setup && ./configure && make

compiler:
    - clang
    - gcc

notifications:
  irc:
    channels:
      - "chat.freenode.net#Monitoring-Plugins"
    on_success: change
    on_failure: always
    skip_join: true
#  email: false
